--# Alterar o estado do PDB

ALTER PLUGGABLE DATABASE DBPROD OPEN READ ONLY;

ALTER PLUGGABLE DATABASE DBPROD OPEN;


--# Fechar o PDB
ALTER PLUGGABLE DATABASE DBPROD CLOSE IMMEDIATE;


--# Salvar o estado do PDB
ALTER PLUGGABLE DATABASE DBPROD SAVE STATE;
