--#CRIAR USUARIO
CREATE USER LUCASG IDENTIFIED BY SENHA
DEFAULT TABLESPACE ;




--# EVIDENCIAR TESTE DE CONEXAO DE USUARIO
COL INSTANCIA      FOR A10
COL DATABASE       FOR A10
COL SID_SESSAO     FOR A11
COL USUARIO_BANCO  FOR A20
COL HOST_BANCO     FOR A20
COL USUARIO_SO     FOR A20
COL HOST_SESSAO    FOR A30
SELECT SYS_CONTEXT('USERENV', 'INSTANCE_NAME') AS INSTANCIA,
       SYS_CONTEXT('USERENV', 'DB_NAME')       AS DATABASE,
       SYS_CONTEXT('USERENV', 'SID')           AS SID_SESSAO,
       SYS_CONTEXT('USERENV', 'SESSION_USER')  AS USUARIO_BANCO,
       SYS_CONTEXT('USERENV', 'SERVER_HOST')   AS HOST_BANCO,
       SYS_CONTEXT('USERENV', 'OS_USER')       AS USUARIO_SO,
       SYS_CONTEXT('USERENV', 'HOST')          AS HOST_SESSAO FROM DUAL ;





--#LISTAR USUARIOS CADASTRADOS
SET PAGES 1000 LINES 190 LONG 10000;
COL USUARIO FOR A25
COL STATUS FOR A16
COL PROFILE FOR A18
COL CRIACAO FOR A22
COL VALIDADE FOR A16
COL BLOQUEIO FOR A16
select u.username as usuario,
u.account_status as status,
u.profile,
to_char (u.created, 'YYYY-MM-DD HH24:MI') as criacao,
to_char (u.expiry_date, 'YYYY-MM-DD HH24:MI') as validade,
to_char (u.lock_date, 'YYYY-MM-DD HH24:MI') as bloqueio
from dba_users u
WHERE account_status='OPEN'
--where username LIKE'INTER%'
order by criacao;
