--criar usuário de consulta

CREATE USER DEMACODE IDENTIFIED BY z#SagF8h;

--grant de consulta nas tabelas

GRANT CREATE SESSION TO DEMACODE;

GRANT SELECT ON URENAUXVIEW.PCP_ITGRMP TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_PRDGRADE TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_GRUPO TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PCP_FCAPLIC TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.TRA_TRANSITEM TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.TRA_TRANSACAO TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.GER_OPERACAO TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PED_PEDIDOI TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PED_PEDIDOC TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_PRODUTO TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PCP_ITGRUPO TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PCP_ITGRUPOGRD TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_TIPOCLAS TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_PRODUTOCLAS TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_CLASSIFICACAO TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PED_TABPRECOC TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PED_TABPRECOI TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PED_TABPRECOG TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_GRUPOADIC TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_GRUPOCOMP TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_COMPOSICAOC TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.PRD_PRDINFO TO DEMACODE;
GRANT SELECT ON URENAUXVIEW.VR_PRD_SALDO TO DEMACODE;

--testar conexão ao usuário:
CONN DEMACODE /z#SagF8h
