[Oracle Comandos]

--Criar Usuarios--

CREATE USER LUCASG IDENTIFIED BY --SENHA--
DEFAULT TABLESPACE; --NOME DA TABLESPACE--

-- Se for omitido a default tablespace e temporary tablespace o vai ser atribuido o padrão que é a tablespace SYSTEM e TEMP--


--CHECAR AS TABLESPACES USADAS NA CRIAÇAO DO USUARIO--

SELECT USERNAME, DEFAULT_TABLESPACE,TEMPORARY_TABLESPACE FROM DBA_USERS WHERE USERNAME= 'EXEMPLO';



--ALTERAR SENHA--

ALTER USER EXEMPLO IDENTIFIED BY 1234;



--DESBLOQUEAR USUARIO--

ALTER USER EXEMPLO IDENTIFIED BY 1234 ACCOUNT UNLOCK;



--BLOQUEANDO USUARIO--

ALTER USER EXEMPLO ACCOUNT LOCK;



--EXCLUINDO USUARIO--

DROP USER EXEMPLO;



--LIBERAR PRIVILEGIOS--

GRANT CREATE SESSION TO EXEMPLO;      -- SÓ COLOCAR O PRIVILEGIO DESEJADO--



--PRIVILEGIOS DE OBJETO--

GRANT SELECT, UPDATE, INSERT, ON NOME_TABELA TO EXEMPLO;



--CRIAR TABLESPACE--

CREATE TABLESPACE NOME_TABLESPACE
DATAFILE 'u01/apporacle/oradata/RHINO/ts_lucasg01.dbf' -- EXEMPLO-- -- LOCALIZAÇAO VAI MUDAR--
SIZE 100M AUTOEXTEND OFF;



--ALTERAR QUOTA DE USUARIO--

ALTER USER NOME_USUARIO QUOTA 20M ON TABLE_NAME;




--CRIAR TABELA--

CREATE TABLE cliente (id_cliente integer, nome varchar2(30), cidade varchar2(20), telefone char(11)) tablespace *NOME TABLESPACE*;



--INSERINDO DADOS NA TABELA LOGADO COM O OWNER DA TABELA--

INSERT INTO cliente values(1, 'Lucas Grana', 'Blumenau', '123456789101')
INSERT INTO cliente values(2, 'Pericles', 'Blumenau', '123456789101')
INSERT INTO cliente values(3, 'Rafael', 'Blumenau', '123456789101')                     --EXEMPLO--
INSERT INTO cliente values(4, 'Lucas Kraus', 'Blumenau', '123456789101')
INSERT INTO cliente values(5, 'Fabricio', 'Blumenau', '123456789101')
INSERT INTO cliente values(6, 'Dulci', 'Blumenau', '123456789101');



--USUARIO DE LEITURA--

CREATE USER Leitura idenfied by @@teste
DEFAULT_TABLESPACE --NOME TABLESPACE--;

GRANT CREATE SESSION TO Leitura;
GRANT SELECT ON TABLESPACE_NAME TABLE_NAME TO Leitura;

--HABILITAR RECYCLE BIN--

ALTER SESSION SET recyclebin = ON;
ALTER SYSTEM SET recyclebin = ON;

--DESABILITAR RECYCLE BIN--

ALTER SESSION SET recyclebin = OFF;
ALTER SYSTEM SET recyclebin = OFF;



--VERIFICAR QUAIS ROLES ESTAO HABILITADAS PARA O USUARIO--

select * from session_roles;
