--#CRIAR SINONIMO ORACLE

CREATE OR REPLACE SYNONYM FU_CRIPTOGRAFA FOR FU_CRIPTOGRAFA@MetisaDba_UNI3 ;

ONDE FU_CRIPTOGRAFA = NOME SINONIMO

FOR FU_CRIPTOGRAFA = NOME DO OBJETO

@MetisaDba_UNI3 = NOME DB_LINK
